app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index),
    path('admin/', admin.site.urls),
    path("mactaquac/", include("mactaquac.urls")),
]

app/mactaquac/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = "mactaquac"

router = routers.DefaultRouter()
router.register(r"mediafile", views.MediaFileViewSetSerialized)
router.register(r"item", views.ItemViewSetSerialized)

urlpatterns = [
    path("", views.index, name="index"),
    path("mediafiles/", views.MediaFileListView.as_view(), name="mediafiles"),
    path("mediafiles/<int:pk>/", views.MediaFileDetailView.as_view(), name="mediafile"),
    path("api/", include(router.urls), name="api"),
    path("download/<str:filename>/", views.download_media, name="download_media")
]

app/mactaquac/models.py
from django.db import models
from django.utils import timezone

class Item(models.Model):
    identifier = models.CharField(max_length=255, unique=True)
    title = models.CharField(default="[NONE]")
    collection = models.CharField(max_length=50, default="[NONE]")
    updated = models.BooleanField(default=False)

    def __str__(self):
        return self.identifier

class Wrapper(models.Model):
    name = models.CharField(max_length=255, unique=True)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name
    
class VideoCodec(models.Model):
    name = models.CharField(max_length=255, unique=True)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class AudioCodec(models.Model):
    name = models.CharField(max_length=255, unique=True)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class MediaFile(models.Model):
    TYPES = {
        "audio": "audio",
        "video": "video",
        "textual": "textual"
    }
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="mediafiles")
    type = models.CharField(max_length=255, choices=TYPES)
    filename = models.CharField(unique=True)
    filepath = models.CharField(unique=True)
    storage_location = models.CharField()
    wrapper = models.ForeignKey(Wrapper, on_delete=models.SET_NULL, null=True, blank=True)
    videocodec = models.ForeignKey(VideoCodec, on_delete=models.SET_NULL, null=True, blank=True)
    audiocodec = models.ForeignKey(AudioCodec, on_delete=models.SET_NULL, null=True, blank=True)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    checksum = models.CharField(null=True, blank=True)
    creation_date = models.DateField(null=True, blank=True)
    filesize = models.FloatField(default=0)
    duration_min = models.IntegerField(null=True, blank=True)
    duration_sec = models.IntegerField(null=True, blank=True)
    date_added = models.DateField(default=timezone.now())
    date_modified = models.DateField(null=True, blank=True)

    def find_duplicates(self):
        return MediaFile.objects.filter(checksum=self.checksum)

    def __str__(self):
        return self.filename

app/mactaquac/forms.py
from django import forms

class MediaFileSearchForm(forms.Form):
    item_identifier = forms.CharField(label="item identifier", max_length=55, required=False)
    collection = forms.CharField(label="collection", max_length=15, required=False)
    title = forms.CharField(label="item title", max_length=255, required=False)
    filename = forms.CharField(label="filename", required=False)

class MediaFileFilterForm(forms.Form):
    media_wrapper = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label="Media Wrapper",
        choices=list()
    )
    video_codec = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label="Video Codec",
        choices=list()
    )
    audio_codec = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label="Audio Codec",
        choices=list()
    )
    dimensions_width = forms.IntegerField(
        required=False,
        label="Min. width"
    )

    item_identifier = forms.CharField(label="item identifier", max_length=55, required=False, widget=forms.HiddenInput())
    collection = forms.CharField(label="collection", max_length=15, required=False, widget=forms.HiddenInput())
    title = forms.CharField(label="item title", max_length=255, required=False, widget=forms.HiddenInput())
    filename = forms.CharField(label="filename", required=False, widget=forms.HiddenInput())

    def __init__(self, 
            wrapper_list=None,
            vcodec_list=None,
            acodec_list=None,
            *args, **kwargs):
        super(MediaFileFilterForm, self).__init__(*args, **kwargs)
        if wrapper_list:
            self.fields['media_wrapper'].choices = [
                (wrapper, wrapper)
                for wrapper in wrapper_list
            ]
        if vcodec_list:
            self.fields['video_codec'].choices = [
                (vcodec, vcodec)
                for vcodec in vcodec_list
            ]
        if acodec_list:
            self.fields['audio_codec'].choices = [
                (acodec, acodec)
                for acodec in acodec_list
            ]

app/mactaquac/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.views import generic
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from rest_framework import viewsets

from django_filters.rest_framework import DjangoFilterBackend

from .models import MediaFile, Item, Wrapper, VideoCodec, AudioCodec
from .serializers import MediaFileSerializer, ItemSerializer
from .forms import MediaFileSearchForm, MediaFileFilterForm

from pathlib import Path

MEDIA_ROOT = "/home/app/web/media"

def index(request):
    return render(request, "mactaquac/home.html")
  
class MediaFileListView(generic.FormView):
    template_name = "mactaquac/filelist.html"
    
    def get(self, request, *args, **kwargs):
        form = MediaFileSearchForm(self.request.GET or None)

        #declare variables for initial landing on list page
        query_set = MediaFile.objects.all().order_by("item__identifier", "filename")
        item_identifier = str()
        collection = str()
        title = str()
        filename = str()
        media_wrapper = None
        dimensions_width = None
        video_codec = None
        audio_codec = None

        #Change possible values of filter categories based on query set unique values
        wrapper_list = Wrapper.objects.all()
        vcodec_list = VideoCodec.objects.all()
        acodec_list = AudioCodec.objects.all()

        if form.is_valid():
            #Get data from request
            item_identifier = request.GET.get("item_identifier")
            collection = request.GET.get("collection")
            title = request.GET.get("title")
            filename = request.GET.get("filename")
            media_wrapper = request.GET.getlist("media_wrapper", None)
            video_codec = request.GET.getlist("video_codec", None)
            audio_codec = request.GET.getlist("audio_codec", None)
            dimensions_width = request.GET.get("dimensions_width", None)

            #Filter query set with search
            if item_identifier:
                query_set = query_set.filter(item__identifier=item_identifier.strip().upper())
            if collection:
                query_set = query_set.filter(item__collection=collection.strip().upper())
            if title:
                query_set = query_set.filter(item__title__contains=title.strip())
            if filename:
                query_set = query_set.filter(filename__contains=filename)

            #Make list of filter values before applying the filters
            wrapper_list = Wrapper.objects.filter(id__in=query_set.values("wrapper"))
            vcodec_list = VideoCodec.objects.filter(id__in=query_set.values("videocodec"))
            acodec_list = AudioCodec.objects.filter(id__in=query_set.values("audiocodec"))

            if media_wrapper:
                query_set = query_set.filter(wrapper__name__in=media_wrapper)
            if video_codec:
                query_set = query_set.filter(videocodec__name__in=video_codec)
            if audio_codec:
                query_set = query_set.filter(audiocodec__name__in=audio_codec)
            if dimensions_width:
                query_set = query_set.filter(width__gt=dimensions_width)

        #Set up pagination of query set
        paginator = Paginator(query_set, 25)
        page = request.GET.get('page')
        try:
            query_set = paginator.page(page)
        except PageNotAnInteger:
            query_set = paginator.page(1)
        except EmptyPage:
            query_set = paginator.page(paginator.num_pages)

        #add filter form with inherited intial values
        filter_form = MediaFileFilterForm(
            initial={
                "media_wrapper": media_wrapper if media_wrapper else None,
                "video_codec": video_codec if video_codec else None,
                "audio_codec": audio_codec if audio_codec else None,
                "dimensions_width": dimensions_width if dimensions_width else None,
                "item_identifier": item_identifier if item_identifier else None,
                "collection": collection if collection else None,
                "title": title if title else None,
                "filename": filename if filename else None
            },
            wrapper_list=wrapper_list,
            vcodec_list=vcodec_list,
            acodec_list=acodec_list
        )

        return self.render_to_response(self.get_context_data(form=form, mediafiles=query_set, filter_form=filter_form)) 

class MediaFileDetailView(generic.DetailView):
    model = MediaFile
    template_name = "mactaquac/mediafile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["duplicates"] = MediaFile.find_duplicates()
        return context
    
class MediaFileViewSetSerialized(viewsets.ModelViewSet):
    serializer_class = MediaFileSerializer
    queryset = MediaFile.objects.all().order_by("id")
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["filename", "item__identifier", "type", "checksum"]

class ItemViewSetSerialized(viewsets.ModelViewSet):
    serializer_class = ItemSerializer
    queryset = Item.objects.all().order_by("identifier")
    lookup_field = "identifier"

    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["identifier", "collection", "updated"]

def download_media(request, filename):
    filepath = MediaFile.objects.get(filename=filename).filepath
    safe_path: Path = Path(MEDIA_ROOT) / filepath
    if not str(safe_path).startswith(MEDIA_ROOT):
        raise Http404("Invalid file path.")

    elif not safe_path.exists():
        raise Http404("File not found.")

    else:
        response = HttpResponse()
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = f'attachment; filename="{filename}"'

        # This tells Nginx to serve the file
        response['X-Accel-Redirect'] = f"/media/{filepath}"

        return response
    

app/mactaquac/templates/mactaquac/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<link rel="stylesheet" href="{% static 'mactaquac/style.css' %}">

<head>
    <title>{% block title %}Mactaquac DAMS{% endblock %}</title>
</head>

<body>
    <div id="header">
        <h1>Mactaquac DAMS</h1>
        <ul id="navbar">
            <li><a href="{% url 'mactaquac:index' %}">Home</a></li>
            <li><a href="{% url 'mactaquac:mediafiles' %}">Media Files</a></li>
        </ul>
        <br>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        <hr>
        <p>
            Mactaquac v. 0.2.1
        </br>
            Source code available <a href="https://github.com/sidesg/mactaquac">here</a>
        </p>
    </div>
</body>

</html>

app/mactaquac/templates/mactaquac/filelist.html
{% extends "mactaquac/base.html" %}
{% load mactaquac_extras %}
{% block title %}Mactaquac DAMS: Items{% endblock %}
{% block content %}
<h1>Media Files</h1>
<form method="get">
  {{ form }}
  <button type="submit", value="Search">Search</button>
</form>

<div class="wrapper">
    <div class="sidebar">
        <form method="get">
            {{ filter_form }}
            <button type="submit", value="Filter">Filter</button>
        </form>
    </div>
{% if mediafiles %}
    <div class="main">
        <table>
            <tr>
                <th>Item ID</th>
                <th>Filename</th>
                <th>Duration</th>
                <th>Size (MB)</th>
                <th>Item title</th>
                <th>Collection</th>
                <th>Wrapper</th>
                <th>Video codec</th>
                <th>Audio codec</th>
                <th>Resolution</th>
                <th>Created</th>
                <th>Download</th>
            </tr>
            {% for mediafile in mediafiles %}
            <tr>
                <td><a href="{% url 'mactaquac:mediafile' mediafile.pk %}">{{ mediafile.item }}</a></td>
                <td>{{ mediafile.filename }}</td>
                <td>{{ mediafile.duration_min }}:{% if mediafile.duration_sec < 10 %}0{{ mediafile.duration_sec }}{% else %}{{ mediafile.duration_sec }}{% endif %}</td>
                <td>{{ mediafile.filesize }}</td>
                <td>{{ mediafile.item.title }}</td>
                <td>{{ mediafile.item.collection }}</td>
                <td>{{ mediafile.wrapper }}</td>
                <td>{{ mediafile.videocodec }}</td>
                <td>{{ mediafile.audiocodec }}</td>
                <td>{{ mediafile.width }} x {{ mediafile.height }}</td>
                <td>{{ mediafile.creation_date|date:"Y-m-d" }}</td>
                <td><a href="{% url 'mactaquac:download_media' mediafile.filename %}">download</a></td>
            </tr>
            {% endfor %}
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if mediafiles.has_previous %}
                <a href="?{% url_replace request 'page' 1 %}">&laquo; first</a>
                <a href="?{% url_replace request 'page' mediafiles.previous_page_number %}">previous</a>
                {% endif %}
                
                <span class="current">
                    Page {{ mediafiles.number }} of {{ mediafiles.paginator.num_pages }}.
                </span>
                
                {% if mediafiles.has_next %}
                <a href="?{% url_replace request 'page' mediafiles.next_page_number %}">next</a>
                <a href="?{% url_replace request 'page' mediafiles.paginator.num_pages %}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% else %}
    <div class="main">    
        <p>No media files to display.</p>
    </div>
</div>
{% endif %}
{% endblock %}

app/mactaquac/templates/mactaquac/home.html
{% extends "mactaquac/base.html" %}
{% block title %}Mactaquac homepage{% endblock %}
{% block content %}
<p>The Mactaquac Digital Asset Mananagement System is an interface to search for media files based on their metadata.</p>
{% endblock %}

app/mactaquac/templates/mactaquac/mediafile.html
{% extends "mactaquac/base.html" %}
{% block title %}Mactaquac DAMS: Items{% endblock %}
{% block content %}

{% if mediafile %}

<h1>{{ mediafile.filename }} ({{ mediafile.type }} file)</h1>
<ul>
    <li>Storage location: {{ mediafile.storage_location }} (<a href="{% url 'mactaquac:download_media' mediafile.filename %}">download</a>)</li>
    <li>File created {{ mediafile.creation_date|date:"Y-m-d" }}</li>
    <li>Added to Mactaquac {{ mediafile.date_added|date:"Y-m-d" }}</li>
    {% if mediafile.date_modified %}
    <li>Last modified {{ mediafile.date_modified|date:"Y-m-d" }}</li>
    {% endif %}
</ul>

<div>
    <h2>Item information</h2>
    <ul>
        <li>Item: {{ mediafile.item.identifier }}</li>
        <li>Item title: {{ mediafile.item.title }}</li>
        <li>Collection: {{ mediafile.item.collection }}</li>
    </ul>
</div>
<div>
    <h2>Extent</h2>
    <ul>
        <li>File size (MB): {{ mediafile.filesize }}</li>
        <li>Duration: {{ mediafile.duration_min }}:{% if mediafile.duration_sec < 10 %}0{{ mediafile.duration_sec }}{% else %}{{ mediafile.duration_sec }}{% endif %}</li>
    </ul>
</div>
<div>
    <h2>Technical metadata</h2>
    <ul>
        <li>Wrapper: {{ mediafile.wrapper }}</li>
        <li>Video codec: {{ mediafile.videocodec }}</li>
        <li>Audio codec: {{ mediafile.audiocodec }}</li>
        <li>Resolution: {{ mediafile.width }} x {{ mediafile.height }}</li>
        <li>Checksum (md5): {{ mediafile.checksum }}</li>
    </ul>
</div>

{% else %}

<p>No media file to display.</p>

{% endif %}
{% endblock %}